// quotes.js — Curated movie dialogues mapped to personality types

const quotes = {
  gangster: [
    { movie: "The Godfather", quote: "I'm gonna make him an offer he can't refuse.", year: 1972 },
    { movie: "Scarface", quote: "Say hello to my little friend!", year: 1983 },
    { movie: "Goodfellas", quote: "As far back as I can remember, I always wanted to be a gangster.", year: 1990 },
    { movie: "The Dark Knight", quote: "Why so serious?", year: 2008 },
    { movie: "Pulp Fiction", quote: "English, motherf***er! Do you speak it?", year: 1994 },
    { movie: "The Godfather", quote: "Leave the gun. Take the cannoli.", year: 1972 },
    { movie: "Scarface", quote: "In this country, you gotta make the money first. Then when you get the money, you get the power.", year: 1983 },
    { movie: "Casino", quote: "When you love someone, you've gotta trust them. There's no other way.", year: 1995 },
    { movie: "Goodfellas", quote: "Funny how? I mean, funny like I'm a clown? I amuse you?", year: 1990 },
    { movie: "The Usual Suspects", quote: "The greatest trick the devil ever pulled was convincing the world he didn't exist.", year: 1995 },
    { movie: "Heat", quote: "Don't let yourself get attached to anything you are not willing to walk out on in 30 seconds flat.", year: 1995 },
    { movie: "Training Day", quote: "King Kong ain't got s*** on me!", year: 2001 },
    { movie: "The Departed", quote: "I'm the guy who does his job. You must be the other guy.", year: 2006 },
    { movie: "Reservoir Dogs", quote: "Are you gonna bark all day, little doggie, or are you gonna bite?", year: 1992 },
    { movie: "American Gangster", quote: "The loudest one in the room is the weakest one in the room.", year: 2007 },
    { movie: "Boyz n the Hood", quote: "Either they don't know, don't show, or don't care about what's going on in the hood.", year: 1991 },
    { movie: "Snatch", quote: "Do you know what 'nemesis' means?", year: 2000 },
    { movie: "City of God", quote: "If you run, the beast catches you; if you stay, the beast eats you.", year: 2002 },
    { movie: "The Untouchables", quote: "You wanna know how to get Capone? They pull a knife, you pull a gun.", year: 1987 },
    { movie: "A Bronx Tale", quote: "There is nothing more tragic than wasted talent.", year: 1993 },
    { movie: "Carlito's Way", quote: "A favor will kill you faster than a bullet.", year: 1993 },
    { movie: "Donnie Brasco", quote: "Fuhgeddaboudit.", year: 1997 },
    { movie: "Once Upon a Time in America", quote: "Noodles, I slipped.", year: 1984 },
    { movie: "The Irishman", quote: "It is what it is.", year: 2019 },
    { movie: "Gangs of New York", quote: "The appearance of law must be upheld, especially while it's being broken.", year: 2002 },
    { movie: "Layer Cake", quote: "Have a plan, and stick to it.", year: 2004 },
    { movie: "Mean Streets", quote: "You don't make up for your sins in church. You do it in the streets.", year: 1973 },
    { movie: "Miller's Crossing", quote: "Nobody knows anybody. Not that well.", year: 1990 },
    { movie: "Public Enemies", quote: "I like baseball, movies, good clothes, fast cars... and you. What else you need to know?", year: 2009 },
    { movie: "Gotti", quote: "New York is the greatest city in the world, my city.", year: 2018 },
    { movie: "Snatch", quote: "You should never underestimate the predictability of stupidity.", year: 2000 },
    { movie: "Lock, Stock and Two Smoking Barrels", quote: "It's been emotional.", year: 1998 },
    { movie: "The Departed", quote: "No one gives it to you. You have to take it.", year: 2006 },
    { movie: "Pulp Fiction", quote: "Just because you are a character doesn't mean you have character.", year: 1994 },
    { movie: "Boyz n the Hood", quote: "Any fool with a d*** can make a baby, but only a real man can raise his children.", year: 1991 },
    { movie: "Gangs of New York", quote: "I don't give a tuppenny f*** about your moral conundrum, you meat-headed sh*tsack.", year: 2002 },
    { movie: "True Romance", quote: "I'm the Anti-Christ. You got me in a vendetta kind of mood.", year: 1993 },
    { movie: "King of New York", quote: "I'm not your problem. I'm just a businessman.", year: 1990 },
    { movie: "Road to Perdition", quote: "Natural law. Sons are put on this earth to trouble their fathers.", year: 2002 },
    { movie: "The Untouchables", quote: "Never stop fighting till the fight is done.", year: 1987 },
  ],
  pookie: [
    { movie: "Titanic", quote: "I'm the king of the world!", year: 1997 },
    { movie: "Forrest Gump", quote: "Life is like a box of chocolates — you never know what you're gonna get.", year: 1994 },
    { movie: "The Notebook", quote: "If you're a bird, I'm a bird.", year: 2004 },
    { movie: "Good Will Hunting", quote: "It's not your fault.", year: 1997 },
    { movie: "A Walk to Remember", quote: "I might be the one who is supposed to help you.", year: 2002 },
    { movie: "Eternal Sunshine of the Spotless Mind", quote: "Meet me in Montauk.", year: 2004 },
    { movie: "When Harry Met Sally", quote: "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.", year: 1989 },
    { movie: "Pride & Prejudice", quote: "You have bewitched me, body and soul.", year: 2005 },
    { movie: "The Fault in Our Stars", quote: "Okay. Okay.", year: 2014 },
    { movie: "10 Things I Hate About You", quote: "I burn, I pine, I perish.", year: 1999 },
    { movie: "La La Land", quote: "Here's to the ones who dream, foolish as they may seem.", year: 2016 },
    { movie: "Before Sunrise", quote: "I believe if there's any kind of God it wouldn't be in any of us — it'd be in the space between us.", year: 1995 },
    { movie: "Notting Hill", quote: "I'm also just a girl, standing in front of a boy, asking him to love her.", year: 1999 },
    { movie: "Love Actually", quote: "To me, you are perfect.", year: 2003 },
    { movie: "The Princess Bride", quote: "As you wish.", year: 1987 },
    { movie: "Crazy Rich Asians", quote: "Wherever you are in the world, that's where I belong.", year: 2018 },
    { movie: "The Vow", quote: "I vow to fiercely love you in all your forms, now and forever.", year: 2012 },
    { movie: "Me Before You", quote: "You are pretty much the only thing that makes me want to get up in the morning.", year: 2016 },
    { movie: "To All the Boys I've Loved Before", quote: "You're the one I imagined this with.", year: 2018 },
    { movie: "Silver Linings Playbook", quote: "The only way you can beat my crazy was by doing something crazy yourself.", year: 2012 },
    { movie: "About Time", quote: "I just try to live every day as if I've deliberately come back to this one day.", year: 2013 },
    { movie: "Amelie", quote: "At least you'll never be a vegetable.", year: 2001 },
    { movie: "Bridget Jones's Diary", quote: "I like you, very much. Just as you are.", year: 2001 },
    { movie: "You've Got Mail", quote: "I wanted it to be you. I wanted it to be you so badly.", year: 1998 },
    { movie: "Clueless", quote: "As if!", year: 1995 },
    { movie: "Sleepless in Seattle", quote: "It was a million tiny little things that, when you added them all up, they meant we were supposed to be together.", year: 1993 },
    { movie: "500 Days of Summer", quote: "I love how she makes me feel, like anything's possible, or like life is worth it.", year: 2009 },
    { movie: "Jerry Maguire", quote: "You complete me.", year: 1996 },
    { movie: "13 Going on 30", quote: "Love is a battlefield.", year: 2004 },
    { movie: "Pretty Woman", quote: "I want the fairy tale.", year: 1990 },
    { movie: "10 Things I Hate About You", quote: "I hate the way I don't hate you. Not even close, not even a little bit, not even at all.", year: 1999 },
    { movie: "The Princess Bride", quote: "Death cannot stop true love. All it can do is delay it for a while.", year: 1987 },
    { movie: "Love, Rosie", quote: "No matter where you are, or what you're doing, or who you're with, I will always, honestly, truly, completely, love you.", year: 2014 },
    { movie: "A Walk to Remember", quote: "Our love is like the wind. I can't see it, but I can feel it.", year: 2002 },
    { movie: "The Fault in Our Stars", quote: "I fell in love the way you fall asleep: slowly, and then all at once.", year: 2014 },
    { movie: "La La Land", quote: "I'm always gonna love you.", year: 2016 },
    { movie: "Crazy, Stupid, Love", quote: "I found my soulmate.", year: 2011 },
    { movie: "Notting Hill", quote: "I live in Notting Hill. You live in Beverly Hills. Everyone in the world knows who you are.", year: 1999 },
    { movie: "Before Sunset", quote: "Baby, you are gonna miss that plane.", year: 2004 },
    { movie: "Moonrise Kingdom", quote: "I love you, but you don't know what you're talking about.", year: 2012 },
  ],
  playboy: [
    { movie: "James Bond: Casino Royale", quote: "The name's Bond. James Bond.", year: 2006 },
    { movie: "Top Gun", quote: "I feel the need… the need for speed!", year: 1986 },
    { movie: "Wolf of Wall Street", quote: "My name is Jordan Belfort. The year I turned 26, I made 49 million dollars.", year: 2013 },
    { movie: "Grease", quote: "Tell me about it, stud.", year: 1978 },
    { movie: "Anchorman", quote: "I'm kind of a big deal. People know me.", year: 2004 },
    { movie: "Iron Man", quote: "I am Iron Man.", year: 2008 },
    { movie: "American Psycho", quote: "I have to return some videotapes.", year: 2000 },
    { movie: "Fight Club", quote: "I look like you wanna look, I f*** like you wanna f***, I am smart, capable, and most importantly, I am free.", year: 1999 },
    { movie: "Catch Me If You Can", quote: "Dad, I'm the bad guy.", year: 2002 },
    { movie: "The Social Network", quote: "You're going to go through life thinking that girls don't like you because you're a tech geek. I want you to know, from the bottom of my heart, that won't be true.", year: 2010 },
    { movie: "Crazy, Stupid, Love", quote: "Be better than the Gap.", year: 2011 },
    { movie: "Hitch", quote: "Basic principle: no matter what, no matter when, no matter who — any man has a chance to sweep any woman off her feet.", year: 2005 },
    { movie: "Iron Man 2", quote: "I have successfully privatized world peace.", year: 2010 },
    { movie: "Ocean's Eleven", quote: "Are you in or are you out? Right now.", year: 2001 },
    { movie: "Ferris Bueller's Day Off", quote: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", year: 1986 },
    { movie: "Casino Royale", quote: "I have no armor left. You've stripped it from me.", year: 2006 },
    { movie: "Alfie", quote: "I myself subscribe more to the European philosophy of life, my priorities leaning towards wine, women... well, actually, that's about it.", year: 2004 },
    { movie: "Cruel Intentions", quote: "You see, I am the only one who can appreciate how truly magnificent you are.", year: 1999 },
    { movie: "Dirty Dancing", quote: "Nobody puts Baby in a corner.", year: 1987 },
    { movie: "The Italian Job", quote: "I trust everyone. It's the devil inside them I don't trust.", year: 2003 },
    { movie: "Focus", quote: "There's two kinds of people in this world: there's hammers and there's nails.", year: 2015 },
    { movie: "Cocktail", quote: "Cough up a buck, you cheap bastard, I'll pour you a Dewar's.", year: 1988 },
    { movie: "Hustlers", quote: "The whole country is a strip club. You've got people tossing the money, and people doing the dance.", year: 2019 },
    { movie: "Saturday Night Fever", quote: "I know everything about you... You're a nice girl, and you're a good dancer.", year: 1977 },
    { movie: "Crazy, Stupid, Love", quote: "I will help you rediscover your manhood. Do you have any idea where you lost it?", year: 2011 },
    { movie: "Risky Business", quote: "Sometimes you just gotta say, 'What the f***'.", year: 1983 },
    { movie: "Boiler Room", quote: "They say money can't buy happiness? Look at the f***ing smile on my face.", year: 2000 },
    { movie: "Two for the Money", quote: "You're a lemon. And I'm gonna make lemonade.", year: 2005 },
    { movie: "Rounders", quote: "If you can't spot the sucker in your first half hour at the table, then you are the sucker.", year: 1998 },
    { movie: "Blow", quote: "Money isn't real, George. It doesn't matter. It only seems like it does.", year: 2001 },
    { movie: "The Wolf of Wall Street", quote: "I'm not leaving! I'm not leaving! I'm not f***ing leaving!", year: 2013 },
    { movie: "Iron Man", quote: "Is it better to be feared or respected? I say, is it too much to ask for both?", year: 2008 },
    { movie: "American Psycho", quote: "Do you like Huey Lewis and The News?", year: 2000 },
    { movie: "Top Gun", quote: "You can be my wingman any time.", year: 1986 },
    { movie: "Hitch", quote: "Never lie, steal, cheat, or drink. But if you must lie, lie in the arms of the one you love.", year: 2005 },
    { movie: "Ocean's Eleven", quote: "You're a thief and a liar. I only lied about being a thief.", year: 2001 },
    { movie: "Catch Me If You Can", quote: "Stop chasing me!", year: 2002 },
    { movie: "The Great Gatsby", quote: "A little party never killed nobody.", year: 2013 },
    { movie: "Zoolander", quote: "I'm pretty sure there's a lot more to life than being really, really, ridiculously good looking.", year: 2001 },
    { movie: "Magic Mike", quote: "I am the magic.", year: 2012 },
  ],
  sigma: [
    { movie: "Fight Club", quote: "You are not your job. You're not how much money you have in the bank.", year: 1999 },
    { movie: "The Dark Knight Rises", quote: "A hero can be anyone, even a man doing something as simple as putting a coat around a young boy's shoulders.", year: 2012 },
    { movie: "Drive", quote: "There's no good side to that road.", year: 2011 },
    { movie: "No Country for Old Men", quote: "What's the most you've ever lost in a coin toss?", year: 2007 },
    { movie: "Whiplash", quote: "There are no two words in the English language more harmful than 'good job'.", year: 2014 },
    { movie: "The Social Network", quote: "If you were the inventors of Facebook, you'd have invented Facebook.", year: 2010 },
    { movie: "Interstellar", quote: "We used to look up at the sky and wonder at our place in the stars. Now we just look down and worry about our place in the dirt.", year: 2014 },
    { movie: "There Will Be Blood", quote: "I'm finished!", year: 2007 },
    { movie: "Inception", quote: "An idea is like a virus, resilient, highly contagious.", year: 2010 },
    { movie: "The Revenant", quote: "I ain't afraid to die anymore. I done it already.", year: 2015 },
    { movie: "John Wick", quote: "People keep asking if I'm back. Yeah, I'm thinking I'm back.", year: 2014 },
    { movie: "Mad Max: Fury Road", quote: "WITNESS ME!", year: 2015 },
    { movie: "Taxi Driver", quote: "You talkin' to me?", year: 1976 },
    { movie: "Nightcrawler", quote: "I will never ask you to do anything that I wouldn't do myself.", year: 2014 },
    { movie: "Blade Runner", quote: "I've seen things you people wouldn't believe.", year: 1982 },
    { movie: "The Matrix", quote: "I can only show you the door. You're the one that has to walk through it.", year: 1999 },
    { movie: "Seven Samurai", quote: "Danger always strikes when everything seems fine.", year: 1954 },
    { movie: "No Country for Old Men", quote: "You can't stop what's coming. It ain't all waiting on you.", year: 2007 },
    { movie: "Collateral", quote: "Someday? Someday my dream will come? One night you will wake up and discover it never happened.", year: 2004 },
    { movie: "The Equalizer", quote: "When you pray for rain, you gotta deal with the mud too.", year: 2014 },
    { movie: "I Am Legend", quote: "I'm not gonna let this happen.", year: 2007 },
    { movie: "The Batman", quote: "They think I am hiding in the shadows. But I am the shadows.", year: 2022 },
    { movie: "Logan", quote: "Nature made me a freak. Man made me a weapon. And God made it last too long.", year: 2017 },
    { movie: "V for Vendetta", quote: "People should not be afraid of their governments. Governments should be afraid of their people.", year: 2005 },
    { movie: "Joker", quote: "I used to think that my life was a tragedy, but now I realize, it's a f***ing comedy.", year: 2019 },
    { movie: "Leon: The Professional", quote: "No women, no kids. That's the rules.", year: 1994 },
    { movie: "Sin City", quote: "Turn the right corner in Sin City, and you can find anything.", year: 2005 },
    { movie: "The Bourne Identity", quote: "I can tell you the license plate numbers of all six cars outside. I can tell you that our waitress is left-handed...", year: 2002 },
    { movie: "Rambo: First Blood", quote: "They drew first blood, not me.", year: 1982 },
    { movie: "Gladiator", quote: "I will win the crowd. I will give them something they have never seen before.", year: 2000 },
    { movie: "Drive", quote: "I don't carry a gun. I drive.", year: 2011 },
    { movie: "First Blood", quote: "To survive a war, you gotta become war.", year: 1982 },
    { movie: "John Wick", quote: "Everything's got a price.", year: 2014 },
    { movie: "The Machinist", quote: "I haven't slept in a year.", year: 2004 },
    { movie: "Donnie Darko", quote: "Destruction is a form of creation.", year: 2001 },
    { movie: "Fight Club", quote: "It's only after we've lost everything that we're free to do anything.", year: 1999 },
    { movie: "No Country for Old Men", quote: "If the rule you followed brought you to this, of what use was the rule?", year: 2007 },
    { movie: "Mad Max: Fury Road", quote: "My name is Max. My world is fire and blood.", year: 2015 },
    { movie: "Nightcrawler", quote: "My motto is if you want to win the lottery you've got to make the money to buy a ticket.", year: 2014 },
    { movie: "The Punisher", quote: "This is not revenge. It's punishment.", year: 2004 },
  ],
  hustler: [
    { movie: "Rocky", quote: "Yo, Adrian! I did it!", year: 1976 },
    { movie: "The Pursuit of Happyness", quote: "Don't ever let somebody tell you that you can't do something. Not even me.", year: 2006 },
    { movie: "Wolf of Wall Street", quote: "Winners use words like 'would' and 'will'.", year: 2013 },
    { movie: "Whiplash", quote: "Not quite my tempo.", year: 2014 },
    { movie: "Rudy", quote: "You're five feet nothin', a hundred and nothin'... and you have nearly a God-given gift.", year: 1993 },
    { movie: "8 Mile", quote: "If you had one shot, or one opportunity to seize everything you ever wanted in one moment, would you capture it?", year: 2002 },
    { movie: "Moneyball", quote: "It's a process. It's a process. It's a process.", year: 2011 },
    { movie: "The Social Network", quote: "A million dollars isn't cool. You know what's cool? A billion dollars.", year: 2010 },
    { movie: "Scarface", quote: "Every day above ground is a good day.", year: 1983 },
    { movie: "The Shawshank Redemption", quote: "Get busy living or get busy dying.", year: 1994 },
    { movie: "Jerry Maguire", quote: "Show me the money!", year: 1996 },
    { movie: "Wall Street", quote: "Greed, for lack of a better word, is good.", year: 1987 },
    { movie: "Gladiator", quote: "What we do in life echoes in eternity.", year: 2000 },
    { movie: "Margin Call", quote: "Be first, be smarter, or cheat.", year: 2011 },
    { movie: "The Founder", quote: "Business is war. It's dog eat dog, rat eat rat.", year: 2016 },
    { movie: "Nightcrawler", quote: "If you want to win the lottery, you have to make the money to buy a ticket.", year: 2014 },
    { movie: "Boiler Room", quote: "Anybody who tells you money is the root of all evil doesn't f***ing have any.", year: 2000 },
    { movie: "The Pursuit of Happyness", quote: "You got a dream... You gotta protect it.", year: 2006 },
    { movie: "Limitless", quote: "I don't have a lot of time. And what time I do have, I don't want to waste.", year: 2011 },
    { movie: "Joy", quote: "Never think that the world owes you anything, because it doesn't.", year: 2015 },
    { movie: "Uncut Gems", quote: "This is how I win.", year: 2019 },
    { movie: "Wall Street: Money Never Sleeps", quote: "Money is a b*tch that never sleeps.", year: 2010 },
    { movie: "Catch Me If You Can", quote: "Two little mice fell in a bucket of cream...", year: 2002 },
    { movie: "Ford v Ferrari", quote: "There's a point at 7,000 RPM... where everything fades.", year: 2019 },
    { movie: "Paid in Full", quote: "A nickel-rock will get you twenty, but a dime-rock will get you life.", year: 2002 },
    { movie: "American Hustle", quote: "People believe what they want to believe.", year: 2013 },
    { movie: "Molly's Game", quote: "You know what makes you feel okay about losing? Winning.", year: 2017 },
    { movie: "The Big Short", quote: "Truth is like poetry. And most people f***ing hate poetry.", year: 2015 },
    { movie: "Baby Driver", quote: "The moment you catch feelings is the moment you catch a bullet.", year: 2017 },
    { movie: "War Dogs", quote: "They call it war. I call it an industry.", year: 2016 },
    { movie: "Wall Street", quote: "Money never sleeps, pal.", year: 1987 },
    { movie: "Glengarry Glen Ross", quote: "Always Be Closing.", year: 1992 },
    { movie: "Scarface", quote: "I always tell the truth. Even when I lie.", year: 1983 },
    { movie: "Jerry Maguire", quote: "Help me, help you.", year: 1996 },
    { movie: "The Pursuit of Happyness", quote: "There is an I in 'happiness', there is no Y in 'happiness', it's an I.", year: 2006 },
    { movie: "Moneyball", quote: "Are you listening? Because I am telling you something important.", year: 2011 },
    { movie: "Margin Call", quote: "There are three ways to make a living in this business: be first, be smarter, or cheat.", year: 2011 },
    { movie: "The Founder", quote: "Persistence. Nothing in the world can take the place of persistence.", year: 2016 },
    { movie: "Jobs", quote: "Here's to the crazy ones. The misfits. The rebels.", year: 2013 },
    { movie: "Goodfellas", quote: "Never rat on your friends and always keep your mouth shut.", year: 1990 },
  ],
  philosopher: [
    { movie: "The Matrix", quote: "What is real? How do you define real?", year: 1999 },
    { movie: "Interstellar", quote: "Love is the one thing we're capable of perceiving that transcends time and space.", year: 2014 },
    { movie: "Her", quote: "The heart's not like a box that gets filled up. It expands in size the more you love.", year: 2013 },
    { movie: "Cloud Atlas", quote: "Our lives are not our own. From womb to tomb, we are bound to others.", year: 2012 },
    { movie: "Contact", quote: "If it's just us — seems like an awful waste of space.", year: 1997 },
    { movie: "The Tree of Life", quote: "There are two ways through life: the way of nature, and the way of grace.", year: 2011 },
    { movie: "Blade Runner 2049", quote: "Dying for the right cause is the most human thing we can do.", year: 2017 },
    { movie: "Arrival", quote: "Despite knowing the journey and where it leads, I embrace it.", year: 2016 },
    { movie: "2001: A Space Odyssey", quote: "I'm sorry, Dave. I'm afraid I can't do that.", year: 1968 },
    { movie: "Melancholia", quote: "The Earth is evil. We don't need to grieve for it.", year: 2011 },
    { movie: "Eternal Sunshine of the Spotless Mind", quote: "How happy is the blameless vestal's lot? The world forgetting, by the world forgot.", year: 2004 },
    { movie: "Donnie Darko", quote: "Every living creature on this Earth dies alone.", year: 2001 },
    { movie: "The Truman Show", quote: "We accept the reality of the world with which we're presented. It's as simple as that.", year: 1998 },
    { movie: "Synecdoche, New York", quote: "The end is built into the beginning.", year: 2008 },
    { movie: "V for Vendetta", quote: "Ideas are bulletproof.", year: 2005 },
    { movie: "The Shawshank Redemption", quote: "Hope is a good thing, maybe the best of things, and no good thing ever dies.", year: 1994 },
    { movie: "Dead Poets Society", quote: "No matter what anybody tells you, words and ideas can change the world.", year: 1989 },
    { movie: "Waking Life", quote: "The trick is to combine your waking rational abilities with the infinite possibilities of your dreams.", year: 2001 },
    { movie: "A Scanner Darkly", quote: "What does a scanner see? Into the head? Down into the heart?", year: 2006 },
    { movie: "Birdman", quote: "A thing is a thing, not what is said of that thing.", year: 2014 },
    { movie: "The Seventh Seal", quote: "Faith is a torment. It is like loving someone who is out there in the darkness but never appears.", year: 1957 },
    { movie: "Solaris", quote: "We don't need other worlds. We need mirrors.", year: 1972 },
    { movie: "Stalker", quote: "Passion is inversely proportional to the amount of real information available.", year: 1979 },
    { movie: "Persona", quote: "The hopeless dream of being - not seeming, but being.", year: 1966 },
    { movie: "The Thin Red Line", quote: "What's this war in the heart of nature?", year: 1998 },
    { movie: "Apocalypse Now", quote: "The horror... the horror.", year: 1979 },
    { movie: "My Dinner with Andre", quote: "I think that New York is the new model for the new concentration camp.", year: 1981 },
    { movie: "Wings of Desire", quote: "When the child was a child, it walked with its arms swinging.", year: 1987 },
    { movie: "Boyhood", quote: "It's constant. The moments, it's just... it's like it's always right now, you know?", year: 2014 },
    { movie: "I Heart Huckabees", quote: "Have you ever transcended space and time?", year: 2004 },
    { movie: "The Matrix Reloaded", quote: "Choice is an illusion created between those with power and those without.", year: 2003 },
    { movie: "Interstellar", quote: "Mankind was born on Earth. It was never meant to die here.", year: 2014 },
    { movie: "Blade Runner", quote: "All those moments will be lost in time, like tears in rain.", year: 1982 },
    { movie: "The Truman Show", quote: "Good morning, and in case I don't see ya, good afternoon, good evening, and good night!", year: 1998 },
    { movie: "Waking Life", quote: "Wake up and live.", year: 2001 },
    { movie: "V for Vendetta", quote: "Beneath this mask there is more than flesh... Beneath this mask there is an idea.", year: 2005 },
    { movie: "Mr. Nobody", quote: "Every path is the right path. Everything could've been anything else.", year: 2009 },
    { movie: "2001: A Space Odyssey", quote: "Its origin and purpose, still a total mystery.", year: 1968 },
    { movie: "Arrival", quote: "Memory is a strange thing. It doesn't work like I thought it did.", year: 2016 },
    { movie: "A Ghost Story", quote: "We build our legacy piece by piece, and maybe the whole world will remember you or maybe just a couple of people.", year: 2017 },
  ],
};

const personalityLabels = {
  gangster: "👊 The Gangster",
  pookie: "🥺 The Pookie",
  playboy: "😎 The Playboy",
  sigma: "🐺 The Sigma",
  hustler: "💰 The Hustler",
  philosopher: "🧠 The Philosopher",
};

function getRandomQuote(personality) {
  const list = quotes[personality] || quotes.gangster;
  return list[Math.floor(Math.random() * list.length)];
}

function formatQuoteMessage(nickname, personality, quoteObj) {
  const label = personalityLabels[personality] || "🎬 Movie Buff";
  return (
    `🎬 *CineQuotes Daily* — just for *${nickname}* (${label})\n\n` +
    `_"${quoteObj.quote}"_\n\n` +
    `— *${quoteObj.movie}* (${quoteObj.year})\n\n` +
    `━━━━━━━━━━━━━━━━━━━━\n` +
    `Reply *MORE* for another quote, or *STOP* to unsubscribe 🙏`
  );
}

module.exports = { quotes, personalityLabels, getRandomQuote, formatQuoteMessage };
